name: Draft Release

on:
  workflow_call:
    secrets:
      BOT_PRIVATE_KEY:
        required: true
        description: Bot's private key for creating releases.

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Extract App's version
        run: echo "APP_VERSION=v$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Create Bot's Access Token
        id: bot-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1
        with:
          client-id: ${{ vars.BOT_CLIENT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Check Release Existence
        id: check
        run: |
          if isAlreadyDrafted=$(gh release view "$APP_VERSION" --json isDraft -q .isDraft); then
            if [ "$isAlreadyDrafted" = "true" ]; then
              echo "isAlreadyDrafted=true" >> "$GITHUB_OUTPUT"
              echo "::notice::$APP_VERSION version exists as draft release"
            else
              echo "::error::$APP_VERSION version was already released to the public"
              exit 1
            fi
          else
            echo "isAlreadyDrafted=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}

      - name: Download compiled app
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          pattern: app-*
          path: dist
          merge-multiple: true

      - name: Extract the changelogs of the new release
        run: node ./scripts/extractLastReleaseChangelog.js > RELEASE_NOTES.md

      - name: Draft a new release
        if: ${{ steps.check.outputs.isAlreadyDrafted == 'false' }}
        run: |
          gh release new $APP_VERSION \
            --title "$APP_VERSION (draft)" \
            --notes-file RELEASE_NOTES.md \
            --draft --latest=false \
            dist/denokv-gui-client* dist/latest*.yml
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}

      - name: Update the release draft
        if: ${{ steps.check.outputs.isAlreadyDrafted == 'true' }}
        run: |
          gh release edit $APP_VERSION --notes-file RELEASE_NOTES.md
          gh release upload $APP_VERSION dist/denokv-gui-client* dist/latest*.yml --clobber
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
