name: Draft Release

on:
  workflow_call:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Download compiled app
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          path: dist
          merge-multiple: true

      - name: Extract the changelogs of the new release
        run: node ./scripts/extractLastReleaseChangelog.js > RELEASE_NOTES.md

      - name: Extract App's version
        run: echo "APP_VERSION=v$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Draft a new release
        run: |
          gh release new $APP_VERSION \
            --title "$APP_VERSION (draft)" \
            --notes-file RELEASE_NOTES.md \
            --draft --latest=false \
            dist/denokv-gui-client* dist/latest*.yml
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Dispatch signing request to OSSign
        id: dispatch
        uses: ossign/actions/workflow/dispatch@main
        with:
          username: ${{ secrets.OSSIGN_USER }}
          token: ${{ secrets.OSSIGN_TOKEN }}
          dispatch_only: true

